version: '3.4'
services:
  Frontend00:
    image: gnes/gnes:latest-alpine
    command: frontend --grpc_port 5566 --port_out 53463 --socket_out PUSH_BIND --port_in
      57908 --socket_in PULL_BIND
    ports:
    - 5566:5566
  Preprocessor10:
    image: gnes/demo:poem-preprocess
    command: --port_in 53463 --socket_in PULL_CONNECT --port_out 56264
      --socket_out PUSH_BIND --host_in Frontend00
  Encoder20:
    image: gnes/demo:poem-encode
    command: --port_in 56264 --socket_in PULL_CONNECT --port_out 64886 --socket_out
      PUSH_CONNECT --host_out Indexer30 --host_in Preprocessor10
  Indexer30:
    image: gnes/demo:poem-vector-index
    command: --port_in 64886 --socket_in PULL_BIND --port_out 57909 --socket_out
      PUSH_CONNECT --host_out Router40
    volumes:
      - ./.cache:/workspace
  Router40:
    image: gnes/gnes:latest-alpine
    command: route --socket_in PULL_BIND --socket_out PUSH_BIND --port_in 57909
      --port_out 57910 --yaml_path ChunkToDocRouter
  Indexer21:
    image: gnes/gnes:latest-alpine
    command: index --port_in 57910 --socket_in PULL_CONNECT --port_out 57911 --socket_out
      PUSH_CONNECT --host_out Router50 --host_in Router40 --yaml_path /yaml/index.yml
    volumes:
      - ./.cache:/workspace
      - ./fulltext-index:/yaml
  Router50:
    image: gnes/gnes:latest-alpine
    command: route --socket_in PULL_BIND --socket_out PUSH_CONNECT --port_in 57911 --port_out 57908
      --host_out Frontend00 --yaml_path DocFillRouter
